In [35]:
import os
import pandas as pd

# Create to one file

In [43]:
data_folder = "trip/2013-to-2020/"
print(data_folder)
df = []

for file in os.listdir(data_folder):
    print('loading file {0}...'.format(file))
    df.append(pd.read_csv(os.path.join(data_folder, file)))

df_master = pd.concat(df)
df_master.to_csv("2013-2020.csv", index= False)

trip/2013-to-2020/
loading file Divvy_Trips_2013.csv...

C:\Users\Bocah\AppData\Local\Temp\ipykernel_12308\2105314297.py:7: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df.append(pd.read_csv(os.path.join(data_folder, file)))

loading file Divvy_Trips_2014-Q3-07.csv...
loading file Divvy_Trips_2014-Q3-0809.csv...
loading file Divvy_Trips_2014-Q4.csv...
loading file Divvy_Trips_2014_Q1Q2.csv...
loading file Divvy_Trips_2015-Q1.csv...
loading file Divvy_Trips_2015-Q2.csv...
loading file Divvy_Trips_2015_07.csv...
loading file Divvy_Trips_2015_08.csv...
loading file Divvy_Trips_2015_09.csv...
loading file Divvy_Trips_2015_Q4.csv...
loading file Divvy_Trips_2016_04.csv...
loading file Divvy_Trips_2016_05.csv...
loading file Divvy_Trips_2016_06.csv...
loading file Divvy_Trips_2016_Q1.csv...
loading file Divvy_Trips_2016_Q3.csv...
loading file Divvy_Trips_2016_Q4.csv...
loading file Divvy_Trips_2017_Q1.csv...
loading file Divvy_Trips_2017_Q2.csv...
loading file Divvy_Trips_2017_Q3.csv...
loading file Divvy_Trips_2017_Q4.csv...
loading file Divvy_Trips_2018_Q1.csv...
loading file Divvy_Trips_2018_Q2.csv...
loading file Divvy_Trips_2018_Q3.csv...
loading file Divvy_Trips_2018_Q4.csv...
loading file Divvy_Trips_2019_Q1.csv...
loading file Divvy_Trips_2019_Q2.csv...
loading file Divvy_Trips_2019_Q3.csv...
loading file Divvy_Trips_2019_Q4.csv...
loading file Divvy_Trips_2020_Q1.csv...

In [45]:
df = pd.read_csv("2013-2020.csv")
df.head()

C:\Users\Bocah\AppData\Local\Temp\ipykernel_12308\284147246.py:1: DtypeWarning: Columns (1,2,4,6,8,9,10,13,14,16,17,19,21,23,24,25,27,28,29,30,31,33,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("2013-2020.csv")

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,4118.0,2013-06-27 12:11,2013-06-27 12:16,480.0,316,85.0,Michigan Ave & Oak St,28.0,Larrabee St & Menomonee St,Customer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4275.0,2013-06-27 14:44,2013-06-27 14:45,77.0,64,32.0,Racine Ave & Congress Pkwy,32.0,Racine Ave & Congress Pkwy,Customer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4291.0,2013-06-27 14:58,2013-06-27 15:05,77.0,433,32.0,Racine Ave & Congress Pkwy,19.0,Loomis St & Taylor St,Customer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4316.0,2013-06-27 15:06,2013-06-27 15:09,77.0,123,19.0,Loomis St & Taylor St,19.0,Loomis St & Taylor St,Customer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4342.0,2013-06-27 15:13,2013-06-27 15:27,77.0,852,19.0,Loomis St & Taylor St,55.0,Halsted St & James M Rochford St,Customer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
df.tail()

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
21670226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2020-03-10 10:40:07,HQ QR,675.0,HQ QR,675.0,41.8899,-87.6803,41.8899,-87.6803,casual
21670227,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2020-03-07 16:14:03,Rush St & Superior St,161.0,Sheridan Rd & Irving Park Rd,240.0,41.8958,-87.6259,41.9542,-87.6544,member
21670228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2020-03-01 13:38:29,Clark St & Lincoln Ave,141.0,Ashland Ave & Division St,210.0,41.9157,-87.6346,41.9035,-87.6677,casual
21670229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2020-03-07 18:13:18,Franklin St & Illinois St,672.0,Stetson Ave & South Water St,264.0,41.8910,-87.6355,41.8868,-87.6223,member
21670230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2020-03-08 13:32:27,Dearborn St & Erie St,110.0,Michigan Ave & Oak St,85.0,41.8940,-87.6293,41.9010,-87.6238,casual

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21670231 entries, 0 to 21670230
Data columns (total 40 columns):
 #   Column                                            Dtype
---  ------                                            -----
 0   trip_id                                           float64
 1   starttime                                         object
 2   stoptime                                          object
 3   bikeid                                            float64
 4   tripduration                                      object
 5   from_station_id                                   float64
 6   from_station_name                                 object
 7   to_station_id                                     float64
 8   to_station_name                                   object
 9   usertype                                          object
 10  gender                                            object
 11  birthday                                          float64
 12  birthyear                                         float64
 13  start_time                                        object
 14  end_time                                          object
 15  01 - Rental Details Rental ID                     float64
 16  01 - Rental Details Local Start Time              object
 17  01 - Rental Details Local End Time                object
 18  01 - Rental Details Bike ID                       float64
 19  01 - Rental Details Duration In Seconds Uncapped  object
 20  03 - Rental Start Station ID                      float64
 21  03 - Rental Start Station Name                    object
 22  02 - Rental End Station ID                        float64
 23  02 - Rental End Station Name                      object
 24  User Type                                         object
 25  Member Gender                                     object
 26  05 - Member Details Member Birthday Year          float64
 27  ride_id                                           object
 28  rideable_type                                     object
 29  started_at                                        object
 30  ended_at                                          object
 31  start_station_name                                object
 32  start_station_id                                  float64
 33  end_station_name                                  object
 34  end_station_id                                    float64
 35  start_lat                                         float64
 36  start_lng                                         float64
 37  end_lat                                           float64
 38  end_lng                                           float64
 39  member_casual                                     object
dtypes: float64(17), object(23)
memory usage: 6.5+ GB

In [73]:
#disini kita mencari mana file yang tidak benar columnya.

# Saring yang tidak NaN, lalu ambil baris pertama (indeks 0) dalam bentuk Series/Satu Row Lengkap
#satu_row = df.loc[df["01 - Rental Details Rental ID"].notna()].iloc[0]

# Tampilkan hasilnya
#print(satu_row)

# Mengubah start_time and end_time to starttime and endtime

In [63]:
folder_path = "tostarttimeandendtime"

for filename in os.listdir(folder_path):
    if filename.endswith(".csv"):
        file_path = os.path.join(folder_path, filename)

        df = pd.read_csv(file_path)
        diubah = False

        if "start_time" in df.columns:
            df.rename(columns={"start_time": "starttime"}, inplace=True)
            diubah = True
        if "end_time" in df.columns:
            df.rename(columns={"end_time": "endtime"}, inplace=True)
            diubah = True
            
        if diubah:
            df.to_csv(file_path, index=False)
            print(f"Berhasil mengubah kolom di file: {filename}")

Berhasil mengubah kolom di file: Divvy_Trips_2017_Q1.csv
Berhasil mengubah kolom di file: Divvy_Trips_2017_Q2.csv
Berhasil mengubah kolom di file: Divvy_Trips_2017_Q3.csv
Berhasil mengubah kolom di file: Divvy_Trips_2017_Q4.csv
Berhasil mengubah kolom di file: Divvy_Trips_2018_Q2.csv
Berhasil mengubah kolom di file: Divvy_Trips_2018_Q3.csv
Berhasil mengubah kolom di file: Divvy_Trips_2018_Q4.csv
Berhasil mengubah kolom di file: Divvy_Trips_2019_Q1.csv
Berhasil mengubah kolom di file: Divvy_Trips_2019_Q3.csv
Berhasil mengubah kolom di file: Divvy_Trips_2019_Q4.csv

# Ulangi proses penyatuan file

In [72]:
data_folder = "trip/2013-to-2020/"
print(data_folder)
df = []

for file in os.listdir(data_folder):
    print('loading file {0}...'.format(file))
    df.append(pd.read_csv(os.path.join(data_folder, file)))

df_master = pd.concat(df)
df_master.to_csv("2013-2020.csv", index= False)

trip/2013-to-2020/
loading file Divvy_Trips_2013.csv...

C:\Users\Bocah\AppData\Local\Temp\ipykernel_12308\2105314297.py:7: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df.append(pd.read_csv(os.path.join(data_folder, file)))

loading file Divvy_Trips_2014-Q3-07.csv...
loading file Divvy_Trips_2014-Q3-0809.csv...
loading file Divvy_Trips_2014-Q4.csv...
loading file Divvy_Trips_2014_Q1Q2.csv...
loading file Divvy_Trips_2015-Q1.csv...
loading file Divvy_Trips_2015-Q2.csv...
loading file Divvy_Trips_2015_07.csv...
loading file Divvy_Trips_2015_08.csv...
loading file Divvy_Trips_2015_09.csv...
loading file Divvy_Trips_2015_Q4.csv...
loading file Divvy_Trips_2016_04.csv...
loading file Divvy_Trips_2016_05.csv...
loading file Divvy_Trips_2016_06.csv...
loading file Divvy_Trips_2016_Q1.csv...
loading file Divvy_Trips_2016_Q3.csv...
loading file Divvy_Trips_2016_Q4.csv...
loading file Divvy_Trips_2017_Q1.csv...
loading file Divvy_Trips_2017_Q2.csv...
loading file Divvy_Trips_2017_Q3.csv...
loading file Divvy_Trips_2017_Q4.csv...
loading file Divvy_Trips_2018_Q1.csv...
loading file Divvy_Trips_2018_Q2.csv...
loading file Divvy_Trips_2018_Q3.csv...
loading file Divvy_Trips_2018_Q4.csv...
loading file Divvy_Trips_2019_Q1.csv...
loading file Divvy_Trips_2019_Q2.csv...
loading file Divvy_Trips_2019_Q3.csv...
loading file Divvy_Trips_2019_Q4.csv...

In [76]:
df = pd.read_csv("2013-2020.csv")
df.head()

C:\Users\Bocah\AppData\Local\Temp\ipykernel_12308\284147246.py:1: DtypeWarning: Columns (1,2,4,6,8,9,10,13,15,16,18,20,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("2013-2020.csv")

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,01 - Rental Details Local End Time,01 - Rental Details Bike ID,01 - Rental Details Duration In Seconds Uncapped,03 - Rental Start Station ID,03 - Rental Start Station Name,02 - Rental End Station ID,02 - Rental End Station Name,User Type,Member Gender,05 - Member Details Member Birthday Year
0,4118.0,2013-06-27 12:11,2013-06-27 12:16,480.0,316,85.0,Michigan Ave & Oak St,28.0,Larrabee St & Menomonee St,Customer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4275.0,2013-06-27 14:44,2013-06-27 14:45,77.0,64,32.0,Racine Ave & Congress Pkwy,32.0,Racine Ave & Congress Pkwy,Customer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4291.0,2013-06-27 14:58,2013-06-27 15:05,77.0,433,32.0,Racine Ave & Congress Pkwy,19.0,Loomis St & Taylor St,Customer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4316.0,2013-06-27 15:06,2013-06-27 15:09,77.0,123,19.0,Loomis St & Taylor St,19.0,Loomis St & Taylor St,Customer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4342.0,2013-06-27 15:13,2013-06-27 15:27,77.0,852,19.0,Loomis St & Taylor St,55.0,Halsted St & James M Rochford St,Customer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21243344 entries, 0 to 21243343
Data columns (total 26 columns):
 #   Column                                            Dtype
---  ------                                            -----
 0   trip_id                                           float64
 1   starttime                                         object
 2   stoptime                                          object
 3   bikeid                                            float64
 4   tripduration                                      object
 5   from_station_id                                   float64
 6   from_station_name                                 object
 7   to_station_id                                     float64
 8   to_station_name                                   object
 9   usertype                                          object
 10  gender                                            object
 11  birthday                                          float64
 12  birthyear                                         float64
 13  endtime                                           object
 14  01 - Rental Details Rental ID                     float64
 15  01 - Rental Details Local Start Time              object
 16  01 - Rental Details Local End Time                object
 17  01 - Rental Details Bike ID                       float64
 18  01 - Rental Details Duration In Seconds Uncapped  object
 19  03 - Rental Start Station ID                      float64
 20  03 - Rental Start Station Name                    object
 21  02 - Rental End Station ID                        float64
 22  02 - Rental End Station Name                      object
 23  User Type                                         object
 24  Member Gender                                     object
 25  05 - Member Details Member Birthday Year          float64
dtypes: float64(11), object(15)
memory usage: 4.1+ GB

In [106]:
df = pd.read_csv(r"trip/2013-to-2020/Divvy_Trips_2018_Q1.csv")
df.rename(columns={"01 - Rental Details Rental ID": "trip_id",
                   "01 - Rental Details Local Start Time":"starttime",
                  "01 - Rental Details Local End Time" : "endtime",
                   "01 - Rental Details Bike ID" : "bikeid",
                   "01 - Rental Details Duration In Seconds Uncapped":"tripduration",
                   "03 - Rental Start Station ID":"from_station_id",
                   "03 - Rental Start Station Name":"from_station_name",
                   "02 - Rental End Station ID":"to_station_id",
                   "02 - Rental End Station Name":"to_station_name",
                   "User Type":"usertype",
                   "Member Gender":"gender",
                   "05 - Member Details Member Birthday Year":"birthyear"                 
                  }, inplace=True)
df.to_csv(r"trip/2013-to-2020/Divvy_Trips_2018_Q1.csv", index=False)
df.head()

,trip_id,starttime,endtime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,Subscriber,Male,1988.0
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),Subscriber,Male,1984.0
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,Subscriber,Male,1989.0
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,Subscriber,Male,1983.0
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,Subscriber,Male,1989.0

In [92]:
data_folder = "trip/2013-to-2020/"
print(data_folder)
df = []

for file in os.listdir(data_folder):
    print('loading file {0}...'.format(file))
    df.append(pd.read_csv(os.path.join(data_folder, file)))

df_master = pd.concat(df)
df_master.to_csv("2013-2020.csv", index= False)

trip/2013-to-2020/
loading file Divvy_Trips_2013.csv...

C:\Users\Bocah\AppData\Local\Temp\ipykernel_12308\2105314297.py:7: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df.append(pd.read_csv(os.path.join(data_folder, file)))

loading file Divvy_Trips_2014-Q3-07.csv...
loading file Divvy_Trips_2014-Q3-0809.csv...
loading file Divvy_Trips_2014-Q4.csv...
loading file Divvy_Trips_2014_Q1Q2.csv...
loading file Divvy_Trips_2015-Q1.csv...
loading file Divvy_Trips_2015-Q2.csv...
loading file Divvy_Trips_2015_07.csv...
loading file Divvy_Trips_2015_08.csv...
loading file Divvy_Trips_2015_09.csv...
loading file Divvy_Trips_2015_Q4.csv...
loading file Divvy_Trips_2016_04.csv...
loading file Divvy_Trips_2016_05.csv...
loading file Divvy_Trips_2016_06.csv...
loading file Divvy_Trips_2016_Q1.csv...
loading file Divvy_Trips_2016_Q3.csv...
loading file Divvy_Trips_2016_Q4.csv...
loading file Divvy_Trips_2017_Q1.csv...
loading file Divvy_Trips_2017_Q2.csv...
loading file Divvy_Trips_2017_Q3.csv...
loading file Divvy_Trips_2017_Q4.csv...
loading file Divvy_Trips_2018_Q1.csv...
loading file Divvy_Trips_2018_Q2.csv...
loading file Divvy_Trips_2018_Q3.csv...
loading file Divvy_Trips_2018_Q4.csv...
loading file Divvy_Trips_2019_Q1.csv...
loading file Divvy_Trips_2019_Q2.csv...
loading file Divvy_Trips_2019_Q3.csv...
loading file Divvy_Trips_2019_Q4.csv...

In [94]:
df = pd.read_csv("2013-2020.csv")
df.head()

C:\Users\Bocah\AppData\Local\Temp\ipykernel_12308\284147246.py:1: DtypeWarning: Columns (1,2,4,6,8,9,10,13,15,16,18,20,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("2013-2020.csv")

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,...,01 - Rental Details Local End Time,01 - Rental Details Bike ID,01 - Rental Details Duration In Seconds Uncapped,03 - Rental Start Station ID,03 - Rental Start Station Name,02 - Rental End Station ID,02 - Rental End Station Name,User Type,Member Gender,05 - Member Details Member Birthday Year
0,4118.0,2013-06-27 12:11,2013-06-27 12:16,480.0,316,85.0,Michigan Ave & Oak St,28.0,Larrabee St & Menomonee St,Customer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4275.0,2013-06-27 14:44,2013-06-27 14:45,77.0,64,32.0,Racine Ave & Congress Pkwy,32.0,Racine Ave & Congress Pkwy,Customer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4291.0,2013-06-27 14:58,2013-06-27 15:05,77.0,433,32.0,Racine Ave & Congress Pkwy,19.0,Loomis St & Taylor St,Customer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4316.0,2013-06-27 15:06,2013-06-27 15:09,77.0,123,19.0,Loomis St & Taylor St,19.0,Loomis St & Taylor St,Customer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4342.0,2013-06-27 15:13,2013-06-27 15:27,77.0,852,19.0,Loomis St & Taylor St,55.0,Halsted St & James M Rochford St,Customer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21243344 entries, 0 to 21243343
Data columns (total 26 columns):
 #   Column                                            Dtype
---  ------                                            -----
 0   trip_id                                           float64
 1   starttime                                         object
 2   stoptime                                          object
 3   bikeid                                            float64
 4   tripduration                                      object
 5   from_station_id                                   float64
 6   from_station_name                                 object
 7   to_station_id                                     float64
 8   to_station_name                                   object
 9   usertype                                          object
 10  gender                                            object
 11  birthday                                          float64
 12  birthyear                                         float64
 13  endtime                                           object
 14  01 - Rental Details Rental ID                     float64
 15  01 - Rental Details Local Start Time              object
 16  01 - Rental Details Local End Time                object
 17  01 - Rental Details Bike ID                       float64
 18  01 - Rental Details Duration In Seconds Uncapped  object
 19  03 - Rental Start Station ID                      float64
 20  03 - Rental Start Station Name                    object
 21  02 - Rental End Station ID                        float64
 22  02 - Rental End Station Name                      object
 23  User Type                                         object
 24  Member Gender                                     object
 25  05 - Member Details Member Birthday Year          float64
dtypes: float64(11), object(15)
memory usage: 4.1+ GB

In [100]:
satu_row = df.loc[df["01 - Rental Details Rental ID"].notna()].iloc[0]
print(satu_row)

trip_id                                                                   NaN
starttime                                                                 NaN
stoptime                                                                  NaN
bikeid                                                                    NaN
tripduration                                                              NaN
from_station_id                                                           NaN
from_station_name                                                         NaN
to_station_id                                                             NaN
to_station_name                                                           NaN
usertype                                                                  NaN
gender                                                                    NaN
birthday                                                                  NaN
birthyear                                                                 NaN
endtime                                                                   NaN
01 - Rental Details Rental ID                                      22178529.0
01 - Rental Details Local Start Time                      2019-04-01 00:02:22
01 - Rental Details Local End Time                        2019-04-01 00:09:48
01 - Rental Details Bike ID                                            6251.0
01 - Rental Details Duration In Seconds Uncapped                        446.0
03 - Rental Start Station ID                                             81.0
03 - Rental Start Station Name                             Daley Center Plaza
02 - Rental End Station ID                                               56.0
02 - Rental End Station Name                        Desplaines St & Kinzie St
User Type                                                          Subscriber
Member Gender                                                            Male
05 - Member Details Member Birthday Year                               1975.0
Name: 17790409, dtype: object

In [104]:
df = pd.read_csv(r"trip/2013-to-2020/Divvy_Trips_2019_Q2.csv")
df.rename(columns={"01 - Rental Details Rental ID": "trip_id",
                   "01 - Rental Details Local Start Time":"starttime",
                  "01 - Rental Details Local End Time" : "endtime",
                   "01 - Rental Details Bike ID" : "bikeid",
                   "01 - Rental Details Duration In Seconds Uncapped":"tripduration",
                   "03 - Rental Start Station ID":"from_station_id",
                   "03 - Rental Start Station Name":"from_station_name",
                   "02 - Rental End Station ID":"to_station_id",
                   "02 - Rental End Station Name":"to_station_name",
                   "User Type":"usertype",
                   "Member Gender":"gender",
                   "05 - Member Details Member Birthday Year":"birthyear"                 
                  }, inplace=True)
df.to_csv(r"trip/2013-to-2020/Divvy_Trips_2019_Q2.csv", index=False)
df.head()

,trip_id,starttime,endtime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,22178529,2019-04-01 00:02:22,2019-04-01 00:09:48,6251,446.0,81,Daley Center Plaza,56,Desplaines St & Kinzie St,Subscriber,Male,1975.0
1,22178530,2019-04-01 00:03:02,2019-04-01 00:20:30,6226,"1,048.0",317,Wood St & Taylor St,59,Wabash Ave & Roosevelt Rd,Subscriber,Female,1984.0
2,22178531,2019-04-01 00:11:07,2019-04-01 00:15:19,5649,252.0,283,LaSalle St & Jackson Blvd,174,Canal St & Madison St,Subscriber,Male,1990.0
3,22178532,2019-04-01 00:13:01,2019-04-01 00:18:58,4151,357.0,26,McClurg Ct & Illinois St,133,Kingsbury St & Kinzie St,Subscriber,Male,1993.0
4,22178533,2019-04-01 00:19:26,2019-04-01 00:36:13,3270,"1,007.0",202,Halsted St & 18th St,129,Blue Island Ave & 18th St,Subscriber,Male,1992.0

# Ulang lagi

In [109]:
data_folder = "trip/2013-to-2020/"
print(data_folder)
df = []

for file in os.listdir(data_folder):
    print('loading file {0}...'.format(file))
    df.append(pd.read_csv(os.path.join(data_folder, file)))

df_master = pd.concat(df)
df_master.to_csv("2013-2020.csv", index= False)

trip/2013-to-2020/
loading file Divvy_Trips_2013.csv...

C:\Users\Bocah\AppData\Local\Temp\ipykernel_12308\2105314297.py:7: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df.append(pd.read_csv(os.path.join(data_folder, file)))

loading file Divvy_Trips_2014-Q3-07.csv...
loading file Divvy_Trips_2014-Q3-0809.csv...
loading file Divvy_Trips_2014-Q4.csv...
loading file Divvy_Trips_2014_Q1Q2.csv...
loading file Divvy_Trips_2015-Q1.csv...
loading file Divvy_Trips_2015-Q2.csv...
loading file Divvy_Trips_2015_07.csv...
loading file Divvy_Trips_2015_08.csv...
loading file Divvy_Trips_2015_09.csv...
loading file Divvy_Trips_2015_Q4.csv...
loading file Divvy_Trips_2016_04.csv...
loading file Divvy_Trips_2016_05.csv...
loading file Divvy_Trips_2016_06.csv...
loading file Divvy_Trips_2016_Q1.csv...
loading file Divvy_Trips_2016_Q3.csv...
loading file Divvy_Trips_2016_Q4.csv...
loading file Divvy_Trips_2017_Q1.csv...
loading file Divvy_Trips_2017_Q2.csv...
loading file Divvy_Trips_2017_Q3.csv...
loading file Divvy_Trips_2017_Q4.csv...
loading file Divvy_Trips_2018_Q1.csv...
loading file Divvy_Trips_2018_Q2.csv...
loading file Divvy_Trips_2018_Q3.csv...
loading file Divvy_Trips_2018_Q4.csv...
loading file Divvy_Trips_2019_Q1.csv...
loading file Divvy_Trips_2019_Q2.csv...
loading file Divvy_Trips_2019_Q3.csv...
loading file Divvy_Trips_2019_Q4.csv...

In [111]:
df = pd.read_csv("2013-2020.csv")
df.head()

C:\Users\Bocah\AppData\Local\Temp\ipykernel_12308\284147246.py:1: DtypeWarning: Columns (2,4,10,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("2013-2020.csv")

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthday,birthyear,endtime
0,4118,2013-06-27 12:11,2013-06-27 12:16,480,316,85,Michigan Ave & Oak St,28,Larrabee St & Menomonee St,Customer,NaN,NaN,NaN,NaN
1,4275,2013-06-27 14:44,2013-06-27 14:45,77,64,32,Racine Ave & Congress Pkwy,32,Racine Ave & Congress Pkwy,Customer,NaN,NaN,NaN,NaN
2,4291,2013-06-27 14:58,2013-06-27 15:05,77,433,32,Racine Ave & Congress Pkwy,19,Loomis St & Taylor St,Customer,NaN,NaN,NaN,NaN
3,4316,2013-06-27 15:06,2013-06-27 15:09,77,123,19,Loomis St & Taylor St,19,Loomis St & Taylor St,Customer,NaN,NaN,NaN,NaN
4,4342,2013-06-27 15:13,2013-06-27 15:27,77,852,19,Loomis St & Taylor St,55,Halsted St & James M Rochford St,Customer,NaN,NaN,NaN,NaN

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21243344 entries, 0 to 21243343
Data columns (total 14 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   starttime          object
 2   stoptime           object
 3   bikeid             int64
 4   tripduration       object
 5   from_station_id    int64
 6   from_station_name  object
 7   to_station_id      int64
 8   to_station_name    object
 9   usertype           object
 10  gender             object
 11  birthday           float64
 12  birthyear          float64
 13  endtime            object
dtypes: float64(2), int64(4), object(8)
memory usage: 2.2+ GB

In [117]:
satu_row = df.loc[df["endtime"].notna()].iloc[0]
print(satu_row)

trip_id                           13518905
starttime               3/31/2017 23:59:07
stoptime                               NaN
bikeid                                5292
tripduration                           857
from_station_id                         66
from_station_name     Clinton St & Lake St
to_station_id                          171
to_station_name      May St & Cullerton St
usertype                        Subscriber
gender                                Male
birthday                               NaN
birthyear                           1989.0
endtime                  4/1/2017 00:13:24
Name: 9993244, dtype: object

# Ulang lagi

In [120]:
data_folder = "trip/2013-to-2020/"
print(data_folder)
df = []

for file in os.listdir(data_folder):
    if file.endswith('.csv'): 
        print('loading file {0}...'.format(file))
        current_df = pd.read_csv(os.path.join(data_folder, file))
        
        current_df.rename(columns={'endtime': 'stoptime'}, inplace=True)
        
        if 'birthday' in current_df.columns:
            current_df.drop(columns=['birthday'], inplace=True)
        df.append(current_df)

df_master = pd.concat(df, ignore_index=True)
df_master.to_csv("2013-2020.csv", index=False)

trip/2013-to-2020/
loading file Divvy_Trips_2013.csv...

C:\Users\Bocah\AppData\Local\Temp\ipykernel_12308\265725071.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  current_df = pd.read_csv(os.path.join(data_folder, file))

loading file Divvy_Trips_2014-Q3-07.csv...
loading file Divvy_Trips_2014-Q3-0809.csv...
loading file Divvy_Trips_2014-Q4.csv...
loading file Divvy_Trips_2014_Q1Q2.csv...
loading file Divvy_Trips_2015-Q1.csv...
loading file Divvy_Trips_2015-Q2.csv...
loading file Divvy_Trips_2015_07.csv...
loading file Divvy_Trips_2015_08.csv...
loading file Divvy_Trips_2015_09.csv...
loading file Divvy_Trips_2015_Q4.csv...
loading file Divvy_Trips_2016_04.csv...
loading file Divvy_Trips_2016_05.csv...
loading file Divvy_Trips_2016_06.csv...
loading file Divvy_Trips_2016_Q1.csv...
loading file Divvy_Trips_2016_Q3.csv...
loading file Divvy_Trips_2016_Q4.csv...
loading file Divvy_Trips_2017_Q1.csv...
loading file Divvy_Trips_2017_Q2.csv...
loading file Divvy_Trips_2017_Q3.csv...
loading file Divvy_Trips_2017_Q4.csv...
loading file Divvy_Trips_2018_Q1.csv...
loading file Divvy_Trips_2018_Q2.csv...
loading file Divvy_Trips_2018_Q3.csv...
loading file Divvy_Trips_2018_Q4.csv...
loading file Divvy_Trips_2019_Q1.csv...
loading file Divvy_Trips_2019_Q2.csv...
loading file Divvy_Trips_2019_Q3.csv...
loading file Divvy_Trips_2019_Q4.csv...

In [122]:
df = pd.read_csv("2013-2020.csv")
df.head()

C:\Users\Bocah\AppData\Local\Temp\ipykernel_12308\284147246.py:1: DtypeWarning: Columns (4,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("2013-2020.csv")

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,4118,2013-06-27 12:11,2013-06-27 12:16,480,316,85,Michigan Ave & Oak St,28,Larrabee St & Menomonee St,Customer,NaN,NaN
1,4275,2013-06-27 14:44,2013-06-27 14:45,77,64,32,Racine Ave & Congress Pkwy,32,Racine Ave & Congress Pkwy,Customer,NaN,NaN
2,4291,2013-06-27 14:58,2013-06-27 15:05,77,433,32,Racine Ave & Congress Pkwy,19,Loomis St & Taylor St,Customer,NaN,NaN
3,4316,2013-06-27 15:06,2013-06-27 15:09,77,123,19,Loomis St & Taylor St,19,Loomis St & Taylor St,Customer,NaN,NaN
4,4342,2013-06-27 15:13,2013-06-27 15:27,77,852,19,Loomis St & Taylor St,55,Halsted St & James M Rochford St,Customer,NaN,NaN

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21243344 entries, 0 to 21243343
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   starttime          object
 2   stoptime           object
 3   bikeid             int64
 4   tripduration       object
 5   from_station_id    int64
 6   from_station_name  object
 7   to_station_id      int64
 8   to_station_name    object
 9   usertype           object
 10  gender             object
 11  birthyear          float64
dtypes: float64(1), int64(4), object(7)
memory usage: 1.9+ GB

# Coba data yang 2020-2026

In [134]:
data_folder = "trip/2020-4-to-2026-05/"
print(data_folder)
df = []

for file in os.listdir(data_folder):
    if file.endswith('.csv'): 
        print('loading file {0}...'.format(file))
        current_df = pd.read_csv(os.path.join(data_folder, file))
        df.append(current_df)

df_master = pd.concat(df, ignore_index=True)
df_master.to_csv("2020-2026.csv", index=False)

trip/2020-4-to-2026-05/
loading file 202004-divvy-tripdata.csv...
loading file 202005-divvy-tripdata.csv...
loading file 202006-divvy-tripdata.csv...
loading file 202007-divvy-tripdata.csv...
loading file 202008-divvy-tripdata.csv...
loading file 202009-divvy-tripdata.csv...
loading file 202010-divvy-tripdata.csv...
loading file 202011-divvy-tripdata.csv...
loading file 202012-divvy-tripdata.csv...
loading file 202101-divvy-tripdata.csv...
loading file 202102-divvy-tripdata.csv...
loading file 202103-divvy-tripdata.csv...
loading file 202104-divvy-tripdata.csv...
loading file 202105-divvy-tripdata.csv...
loading file 202106-divvy-tripdata.csv...
loading file 202107-divvy-tripdata.csv...
loading file 202108-divvy-tripdata.csv...
loading file 202109-divvy-tripdata.csv...
loading file 202110-divvy-tripdata.csv...
loading file 202111-divvy-tripdata.csv...
loading file 202112-divvy-tripdata.csv...
loading file 202201-divvy-tripdata.csv...
loading file 202202-divvy-tripdata.csv...
loading file 202203-divvy-tripdata.csv...
loading file 202204-divvy-tripdata.csv...
loading file 202205-divvy-tripdata.csv...
loading file 202206-divvy-tripdata.csv...
loading file 202207-divvy-tripdata.csv...
loading file 202208-divvy-tripdata.csv...
loading file 202209-divvy-publictripdata.csv...
loading file 202210-divvy-tripdata.csv...
loading file 202211-divvy-tripdata.csv...
loading file 202212-divvy-tripdata.csv...
loading file 202301-divvy-tripdata.csv...
loading file 202302-divvy-tripdata.csv...
loading file 202303-divvy-tripdata.csv...
loading file 202304-divvy-tripdata.csv...
loading file 202305-divvy-tripdata.csv...
loading file 202306-divvy-tripdata.csv...
loading file 202307-divvy-tripdata.csv...
loading file 202308-divvy-tripdata.csv...
loading file 202309-divvy-tripdata.csv...
loading file 202310-divvy-tripdata.csv...
loading file 202311-divvy-tripdata.csv...
loading file 202312-divvy-tripdata.csv...
loading file 202401-divvy-tripdata.csv...
loading file 202402-divvy-tripdata.csv...
loading file 202403-divvy-tripdata.csv...
loading file 202404-divvy-tripdata.csv...
loading file 202405-divvy-tripdata.csv...
loading file 202406-divvy-tripdata.csv...
loading file 202407-divvy-tripdata.csv...
loading file 202408-divvy-tripdata.csv...
loading file 202409-divvy-tripdata.csv...
loading file 202410-divvy-tripdata.csv...
loading file 202411-divvy-tripdata.csv...
loading file 202412-divvy-tripdata.csv...
loading file 202501-divvy-tripdata.csv...
loading file 202502-divvy-tripdata.csv...
loading file 202503-divvy-tripdata.csv...
loading file 202504-divvy-tripdata.csv...
loading file 202505-divvy-tripdata.csv...
loading file 202506-divvy-tripdata.csv...
loading file 202507-divvy-tripdata.csv...
loading file 202508-divvy-tripdata.csv...
loading file 202509-divvy-tripdata.csv...
loading file 202510-divvy-tripdata.csv...
loading file 202511-divvy-tripdata.csv...
loading file 202512-divvy-tripdata.csv...
loading file 202601-divvy-tripdata.csv...
loading file 202602-divvy-tripdata.csv...
loading file 202603-divvy-tripdata.csv...
loading file 202604-divvy-tripdata.csv...
loading file 202605-divvy-tripdata.csv...
loading file Divvy_Trips_2020_Q1.csv...

In [698]:
import pandas as pd
df = pd.read_csv("2020-2026.csv")
df.head()

C:\Users\Bocah\AppData\Local\Temp\ipykernel_21780\1968387333.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("2020-2026.csv")

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152.0,41.8964,-87.6610,41.9322,-87.6586,member
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:54,2020-04-17 17:17:03,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499.0,41.9244,-87.7154,41.9306,-87.7238,member
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:13,2020-04-01 18:08:36,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255.0,41.8945,-87.6179,41.8679,-87.6230,member
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:19,2020-04-07 13:02:31,California Ave & Division St,216,Wood St & Augusta Blvd,657.0,41.9030,-87.6975,41.8992,-87.6722,member
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:59,2020-04-18 11:15:54,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323.0,41.8902,-87.6262,41.9695,-87.6547,casual

In [699]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33696132 entries, 0 to 33696131
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(4), object(9)
memory usage: 3.3+ GB

# Mengubah column name 2020-2026 data agar sama dengan 2013-2020

In [701]:
df["rideable_type"].unique()

array(['docked_bike', 'electric_bike', 'classic_bike', 'electric_scooter'],
      dtype=object)

In [702]:
df.rename(columns={"ride_id": "trip_id",
                    "started_at": "starttime",
                   "ended_at":"stoptime",
                   "start_station_id":"from_station_id",
                   "start_station_name":"from_station_name",
                   "end_station_id":"to_station_id",
                   "end_station_name":"to_station_name",
                   "member_casual":"usertype"
                  }, inplace=True)

In [703]:
df.head()

,trip_id,rideable_type,starttime,stoptime,from_station_name,from_station_id,to_station_name,to_station_id,start_lat,start_lng,end_lat,end_lng,usertype
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152.0,41.8964,-87.6610,41.9322,-87.6586,member
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:54,2020-04-17 17:17:03,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499.0,41.9244,-87.7154,41.9306,-87.7238,member
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:13,2020-04-01 18:08:36,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255.0,41.8945,-87.6179,41.8679,-87.6230,member
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:19,2020-04-07 13:02:31,California Ave & Division St,216,Wood St & Augusta Blvd,657.0,41.9030,-87.6975,41.8992,-87.6722,member
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:59,2020-04-18 11:15:54,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323.0,41.8902,-87.6262,41.9695,-87.6547,casual

In [704]:
df.to_csv("2020-2026.csv", index=False)
df.head()

,trip_id,rideable_type,starttime,stoptime,from_station_name,from_station_id,to_station_name,to_station_id,start_lat,start_lng,end_lat,end_lng,usertype
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152.0,41.8964,-87.6610,41.9322,-87.6586,member
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:54,2020-04-17 17:17:03,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499.0,41.9244,-87.7154,41.9306,-87.7238,member
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:13,2020-04-01 18:08:36,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255.0,41.8945,-87.6179,41.8679,-87.6230,member
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:19,2020-04-07 13:02:31,California Ave & Division St,216,Wood St & Augusta Blvd,657.0,41.9030,-87.6975,41.8992,-87.6722,member
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:59,2020-04-18 11:15:54,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323.0,41.8902,-87.6262,41.9695,-87.6547,casual

# Mengganti value usertype dari 2013-2020 menjadi member dan casual

In [15]:
df = pd.read_csv("2013-2020.csv")
kamus_ubah = {
    'Customer': 'casual',
    'Subscriber': 'member'
}

df['usertype'] = df['usertype'].replace(kamus_ubah)
df.to_csv("2013-2020.csv", index=False)
print(df['usertype'].unique())
df.head()

C:\Users\Bocah\AppData\Local\Temp\ipykernel_21780\2959374316.py:1: DtypeWarning: Columns (4,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("2013-2020.csv")

['casual' 'member' 'Dependent']

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,4118,2013-06-27 12:11,2013-06-27 12:16,480,316,85,Michigan Ave & Oak St,28,Larrabee St & Menomonee St,casual,NaN,NaN
1,4275,2013-06-27 14:44,2013-06-27 14:45,77,64,32,Racine Ave & Congress Pkwy,32,Racine Ave & Congress Pkwy,casual,NaN,NaN
2,4291,2013-06-27 14:58,2013-06-27 15:05,77,433,32,Racine Ave & Congress Pkwy,19,Loomis St & Taylor St,casual,NaN,NaN
3,4316,2013-06-27 15:06,2013-06-27 15:09,77,123,19,Loomis St & Taylor St,19,Loomis St & Taylor St,casual,NaN,NaN
4,4342,2013-06-27 15:13,2013-06-27 15:27,77,852,19,Loomis St & Taylor St,55,Halsted St & James M Rochford St,casual,NaN,NaN

In [17]:
df = pd.read_csv("2020-2026.csv")
df['usertype'].unique()

C:\Users\Bocah\AppData\Local\Temp\ipykernel_21780\3409258366.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("2020-2026.csv")

array(['member', 'casual'], dtype=object)

In [19]:
df = pd.read_csv("2013-2020.csv")
jumlah_dependent = (df['usertype'] == 'Dependent').sum()
total_baris = len(df)

# 4. Hitung persentasenya
persentase = (jumlah_dependent / total_baris) * 100

print(f"Jumlah row 'Dependent' : {jumlah_dependent:,} baris")
print(f"Total seluruh row data : {total_baris:,} baris")
print(f"Persentase             : {persentase:.4f}%")

C:\Users\Bocah\AppData\Local\Temp\ipykernel_21780\183792278.py:1: DtypeWarning: Columns (4,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("2013-2020.csv")

Jumlah row 'Dependent' : 190 baris
Total seluruh row data : 21,243,344 baris
Persentase             : 0.0009%

# dependent into member change

In [22]:
df = pd.read_csv("2013-2020.csv")
kamus_ubah = {
    'Dependent': 'member',
}

df['usertype'] = df['usertype'].replace(kamus_ubah)
df.to_csv("2013-2020.csv", index=False)
print(df['usertype'].unique())
df.head()

C:\Users\Bocah\AppData\Local\Temp\ipykernel_21780\2138458716.py:1: DtypeWarning: Columns (4,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("2013-2020.csv")

['casual' 'member']

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,4118,2013-06-27 12:11,2013-06-27 12:16,480,316,85,Michigan Ave & Oak St,28,Larrabee St & Menomonee St,casual,NaN,NaN
1,4275,2013-06-27 14:44,2013-06-27 14:45,77,64,32,Racine Ave & Congress Pkwy,32,Racine Ave & Congress Pkwy,casual,NaN,NaN
2,4291,2013-06-27 14:58,2013-06-27 15:05,77,433,32,Racine Ave & Congress Pkwy,19,Loomis St & Taylor St,casual,NaN,NaN
3,4316,2013-06-27 15:06,2013-06-27 15:09,77,123,19,Loomis St & Taylor St,19,Loomis St & Taylor St,casual,NaN,NaN
4,4342,2013-06-27 15:13,2013-06-27 15:27,77,852,19,Loomis St & Taylor St,55,Halsted St & James M Rochford St,casual,NaN,NaN

In [24]:
df = pd.read_csv("2020-2026.csv")

C:\Users\Bocah\AppData\Local\Temp\ipykernel_21780\1070312980.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("2020-2026.csv")

In [712]:
df.head()

,trip_id,rideable_type,starttime,stoptime,from_station_name,from_station_id,to_station_name,to_station_id,start_lat,start_lng,end_lat,end_lng,usertype
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152.0,41.8964,-87.6610,41.9322,-87.6586,member
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:54,2020-04-17 17:17:03,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499.0,41.9244,-87.7154,41.9306,-87.7238,member
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:13,2020-04-01 18:08:36,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255.0,41.8945,-87.6179,41.8679,-87.6230,member
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:19,2020-04-07 13:02:31,California Ave & Division St,216,Wood St & Augusta Blvd,657.0,41.9030,-87.6975,41.8992,-87.6722,member
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:59,2020-04-18 11:15:54,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323.0,41.8902,-87.6262,41.9695,-87.6547,casual

# buat trip duration dengan mengurangkan stoptime dengan starttime untuk data 2020-2026

In [714]:
df['starttime'] = pd.to_datetime(df['starttime'], format='mixed')
df['stoptime'] = pd.to_datetime(df['stoptime'], format='mixed')
print("Sedang menghitung tripduration...")
df['tripduration'] = (df['stoptime'] - df['starttime']).dt.total_seconds()
df['tripduration'] = df['tripduration'].round(0).astype('Int64')
print(df[['starttime', 'stoptime', 'tripduration']].head())

Sedang menghitung tripduration...
            starttime            stoptime  tripduration
0 2020-04-26 17:45:14 2020-04-26 18:12:03          1609
1 2020-04-17 17:08:54 2020-04-17 17:17:03           489
2 2020-04-01 17:54:13 2020-04-01 18:08:36           863
3 2020-04-07 12:50:19 2020-04-07 13:02:31           732
4 2020-04-18 10:22:59 2020-04-18 11:15:54          3175

In [715]:
df.head()

,trip_id,rideable_type,starttime,stoptime,from_station_name,from_station_id,to_station_name,to_station_id,start_lat,start_lng,end_lat,end_lng,usertype,tripduration
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152.0,41.8964,-87.6610,41.9322,-87.6586,member,1609
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:54,2020-04-17 17:17:03,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499.0,41.9244,-87.7154,41.9306,-87.7238,member,489
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:13,2020-04-01 18:08:36,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255.0,41.8945,-87.6179,41.8679,-87.6230,member,863
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:19,2020-04-07 13:02:31,California Ave & Division St,216,Wood St & Augusta Blvd,657.0,41.9030,-87.6975,41.8992,-87.6722,member,732
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:59,2020-04-18 11:15:54,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323.0,41.8902,-87.6262,41.9695,-87.6547,casual,3175

In [716]:
#SIMPAN DATA PERMANENT
df.to_csv("2020-2026.csv", index=False)

# cleaning data process

In [326]:
df = pd.read_csv("2013-2020.csv")
df.head()

C:\Users\Bocah\AppData\Local\Temp\ipykernel_21780\284147246.py:1: DtypeWarning: Columns (4,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("2013-2020.csv")

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,4118,2013-06-27 12:11,2013-06-27 12:16,480,316,85,Michigan Ave & Oak St,28,Larrabee St & Menomonee St,casual,NaN,NaN
1,4275,2013-06-27 14:44,2013-06-27 14:45,77,64,32,Racine Ave & Congress Pkwy,32,Racine Ave & Congress Pkwy,casual,NaN,NaN
2,4291,2013-06-27 14:58,2013-06-27 15:05,77,433,32,Racine Ave & Congress Pkwy,19,Loomis St & Taylor St,casual,NaN,NaN
3,4316,2013-06-27 15:06,2013-06-27 15:09,77,123,19,Loomis St & Taylor St,19,Loomis St & Taylor St,casual,NaN,NaN
4,4342,2013-06-27 15:13,2013-06-27 15:27,77,852,19,Loomis St & Taylor St,55,Halsted St & James M Rochford St,casual,NaN,NaN

In [327]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21243344 entries, 0 to 21243343
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   starttime          object
 2   stoptime           object
 3   bikeid             int64
 4   tripduration       object
 5   from_station_id    int64
 6   from_station_name  object
 7   to_station_id      int64
 8   to_station_name    object
 9   usertype           object
 10  gender             object
 11  birthyear          float64
dtypes: float64(1), int64(4), object(7)
memory usage: 1.9+ GB

In [328]:
df.describe()

,trip_id,bikeid,from_station_id,to_station_id,birthyear
count,2.124334e+07,2.124334e+07,2.124334e+07,2.124334e+07,1.597364e+07
mean,1.353282e+07,2.900297e+03,1.800296e+02,1.804237e+02,1.981545e+03
std,7.458730e+06,1.813878e+03,1.320196e+02,1.321890e+02,1.092347e+01
min,3.940000e+03,1.000000e+00,1.000000e+00,1.000000e+00,1.759000e+03
25%,7.186575e+06,1.346000e+03,7.500000e+01,7.500000e+01,1.976000e+03
50%,1.375498e+07,2.705000e+03,1.570000e+02,1.570000e+02,1.985000e+03
75%,2.000710e+07,4.387000e+03,2.680000e+02,2.680000e+02,1.990000e+03
max,2.596290e+07,6.946000e+03,6.730000e+02,6.730000e+02,2.017000e+03

# birthyear

In [330]:
df["birthyear"].unique()

array([  nan, 1979., 1974., 1988., 1986., 1985., 1991., 1959., 1990.,
       1982., 1975., 1972., 1978., 1976., 1989., 1984., 1994., 1987.,
       1981., 1977., 1966., 1997., 1983., 1963., 1971., 1980., 1992.,
       1957., 1969., 1973., 1970., 1962., 1960., 1968., 1961., 1952.,
       1958., 1993., 1906., 1964., 1951., 1956., 1915., 1965., 1967.,
       1949., 1953., 1948., 1955., 1950., 1954., 1945., 1946., 1995.,
       1998., 1943., 1941., 1996., 1931., 1900., 1939., 1944., 1938.,
       1930., 1935., 1940., 1947., 1912., 1899., 1898., 1942., 1909.,
       1936., 1920., 1929., 1901., 1999., 1932., 1934., 1927., 2000.,
       1918., 1933., 1910., 1921., 2016., 1916., 2001., 2003., 2004.,
       2002., 1923., 2017., 1937., 1922., 1895., 2005., 2014., 1759.,
       1790., 1911., 1905., 1904., 1928., 1888., 1889., 1925., 1890.])

In [331]:
df['birthyear'].value_counts()

birthyear
1989.0    919397
1988.0    833369
1990.0    830687
1987.0    805741
1986.0    768543
           ...
2005.0         1
1759.0         1
1790.0         1
1911.0         1
1890.0         1
Name: count, Length: 107, dtype: int64

In [332]:
with pd.option_context('display.max_rows', None):
    print(df['birthyear'].value_counts().sort_index())

birthyear
1759.0         1
1790.0         1
1888.0        20
1889.0         3
1890.0         1
1895.0         1
1898.0        33
1899.0       360
1900.0      1599
1901.0       247
1904.0       243
1905.0         6
1906.0       799
1909.0        57
1910.0         9
1911.0         1
1912.0        57
1915.0       153
1916.0        83
1918.0      1803
1920.0        32
1921.0       981
1922.0        16
1923.0        16
1925.0         2
1927.0        23
1928.0         3
1929.0        85
1930.0       242
1931.0       348
1932.0        14
1933.0        55
1934.0       568
1935.0        50
1936.0        19
1937.0        14
1938.0       750
1939.0      2247
1940.0      1805
1941.0      1695
1942.0      1682
1943.0      2257
1944.0      5205
1945.0      7990
1946.0     14197
1947.0      5789
1948.0     13944
1949.0     24212
1950.0     23573
1951.0     40786
1952.0     54482
1953.0     49747
1954.0     64541
1955.0     73580
1956.0     92459
1957.0     95479
1958.0     99574
1959.0    111196
1960.0    150541
1961.0    154252
1962.0    170999
1963.0    160735
1964.0    183792
1965.0    177275
1966.0    183879
1967.0    167212
1968.0    188361
1969.0    213279
1970.0    239990
1971.0    197876
1972.0    215225
1973.0    210242
1974.0    250776
1975.0    250971
1976.0    274580
1977.0    312914
1978.0    310684
1979.0    356051
1980.0    452455
1981.0    477553
1982.0    564174
1983.0    581814
1984.0    682532
1985.0    713291
1986.0    768543
1987.0    805741
1988.0    833369
1989.0    919397
1990.0    830687
1991.0    763171
1992.0    722219
1993.0    576228
1994.0    416490
1995.0    284765
1996.0    163106
1997.0    104133
1998.0     62725
1999.0     44084
2000.0     27560
2001.0     10476
2002.0      3205
2003.0      1065
2004.0        31
2005.0         1
2014.0         5
2016.0        46
2017.0         7
Name: count, dtype: int64

In [333]:
total_null_birtyear = df['birthyear'].isnull().sum()

In [334]:
total_row = len(df)

In [335]:
print("total null birthyear: ", total_null_birtyear)
print("total birthyear exit: ", total_row - total_null_birtyear)

total null birthyear:  5269702
total birthyear exit:  15973642

In [336]:
import numpy as np
df.loc[(df['birthyear'] < 1910) | (df['birthyear'] > 2004), 'birthyear'] = np.nan

In [337]:
with pd.option_context('display.max_rows', None):
    print(df['birthyear'].value_counts().sort_index())

birthyear
1910.0         9
1911.0         1
1912.0        57
1915.0       153
1916.0        83
1918.0      1803
1920.0        32
1921.0       981
1922.0        16
1923.0        16
1925.0         2
1927.0        23
1928.0         3
1929.0        85
1930.0       242
1931.0       348
1932.0        14
1933.0        55
1934.0       568
1935.0        50
1936.0        19
1937.0        14
1938.0       750
1939.0      2247
1940.0      1805
1941.0      1695
1942.0      1682
1943.0      2257
1944.0      5205
1945.0      7990
1946.0     14197
1947.0      5789
1948.0     13944
1949.0     24212
1950.0     23573
1951.0     40786
1952.0     54482
1953.0     49747
1954.0     64541
1955.0     73580
1956.0     92459
1957.0     95479
1958.0     99574
1959.0    111196
1960.0    150541
1961.0    154252
1962.0    170999
1963.0    160735
1964.0    183792
1965.0    177275
1966.0    183879
1967.0    167212
1968.0    188361
1969.0    213279
1970.0    239990
1971.0    197876
1972.0    215225
1973.0    210242
1974.0    250776
1975.0    250971
1976.0    274580
1977.0    312914
1978.0    310684
1979.0    356051
1980.0    452455
1981.0    477553
1982.0    564174
1983.0    581814
1984.0    682532
1985.0    713291
1986.0    768543
1987.0    805741
1988.0    833369
1989.0    919397
1990.0    830687
1991.0    763171
1992.0    722219
1993.0    576228
1994.0    416490
1995.0    284765
1996.0    163106
1997.0    104133
1998.0     62725
1999.0     44084
2000.0     27560
2001.0     10476
2002.0      3205
2003.0      1065
2004.0        31
Name: count, dtype: int64

# Gender

In [339]:
df["gender"].unique()

array([nan, 'Male', 'Female'], dtype=object)

In [340]:
with pd.option_context('display.max_rows', None):
    print(df['gender'].value_counts().sort_index())

gender
Female     4112553
Male      12235831
Name: count, dtype: int64

In [341]:
df.head()

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,4118,2013-06-27 12:11,2013-06-27 12:16,480,316,85,Michigan Ave & Oak St,28,Larrabee St & Menomonee St,casual,NaN,NaN
1,4275,2013-06-27 14:44,2013-06-27 14:45,77,64,32,Racine Ave & Congress Pkwy,32,Racine Ave & Congress Pkwy,casual,NaN,NaN
2,4291,2013-06-27 14:58,2013-06-27 15:05,77,433,32,Racine Ave & Congress Pkwy,19,Loomis St & Taylor St,casual,NaN,NaN
3,4316,2013-06-27 15:06,2013-06-27 15:09,77,123,19,Loomis St & Taylor St,19,Loomis St & Taylor St,casual,NaN,NaN
4,4342,2013-06-27 15:13,2013-06-27 15:27,77,852,19,Loomis St & Taylor St,55,Halsted St & James M Rochford St,casual,NaN,NaN

In [342]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21243344 entries, 0 to 21243343
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   starttime          object
 2   stoptime           object
 3   bikeid             int64
 4   tripduration       object
 5   from_station_id    int64
 6   from_station_name  object
 7   to_station_id      int64
 8   to_station_name    object
 9   usertype           object
 10  gender             object
 11  birthyear          float64
dtypes: float64(1), int64(4), object(7)
memory usage: 1.9+ GB

In [343]:
#ubah gender jadi category untuk efisiensi memory
df['gender'] = df['gender'].astype('category')

In [344]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21243344 entries, 0 to 21243343
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   starttime          object
 2   stoptime           object
 3   bikeid             int64
 4   tripduration       object
 5   from_station_id    int64
 6   from_station_name  object
 7   to_station_id      int64
 8   to_station_name    object
 9   usertype           object
 10  gender             category
 11  birthyear          float64
dtypes: category(1), float64(1), int64(4), object(6)
memory usage: 1.8+ GB

In [345]:
df["gender"].unique()

[NaN, 'Male', 'Female']
Categories (2, object): ['Female', 'Male']

# trip_id

In [347]:
df["trip_id"].isnull().sum()

0

# starttime

In [349]:
df["starttime"].isnull().sum()

0

# stoptime

In [351]:
df["stoptime"].isnull().sum()

0

# ubah format startime dan stoptime

In [373]:
import pandas as pd

print("1. Sedang memproses starttime (21 juta baris)...")
df['starttime'] = pd.to_datetime(df['starttime'], format='mixed', errors='coerce')
print("✅ starttime SELESAI!")

print("\n2. Sedang memproses stoptime (21 juta baris)...")
df['stoptime'] = pd.to_datetime(df['stoptime'], format='mixed', errors='coerce')
print("✅ stoptime SELESAI!")

1. Sedang memproses starttime (21 juta baris)...
✅ starttime SELESAI!

2. Sedang memproses stoptime (21 juta baris)...
✅ stoptime SELESAI!

In [409]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21243344 entries, 0 to 21243343
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   starttime          object
 2   stoptime           object
 3   bikeid             int64
 4   tripduration       object
 5   from_station_id    int64
 6   from_station_name  object
 7   to_station_id      int64
 8   to_station_name    object
 9   usertype           object
 10  gender             object
 11  birthyear          float64
dtypes: float64(1), int64(4), object(7)
memory usage: 1.9+ GB

In [402]:
df["stoptime"].isnull().sum()

0

In [404]:
df["starttime"].isnull().sum()

0

# karena proses dari ubah startime dan stoptime lama kita akan simpan dulu ke csv dari sini

In [407]:
df.head()

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,4118,2013-06-27 12:11:00,2013-06-27 12:16:00,480,316,85,Michigan Ave & Oak St,28,Larrabee St & Menomonee St,casual,NaN,NaN
1,4275,2013-06-27 14:44:00,2013-06-27 14:45:00,77,64,32,Racine Ave & Congress Pkwy,32,Racine Ave & Congress Pkwy,casual,NaN,NaN
2,4291,2013-06-27 14:58:00,2013-06-27 15:05:00,77,433,32,Racine Ave & Congress Pkwy,19,Loomis St & Taylor St,casual,NaN,NaN
3,4316,2013-06-27 15:06:00,2013-06-27 15:09:00,77,123,19,Loomis St & Taylor St,19,Loomis St & Taylor St,casual,NaN,NaN
4,4342,2013-06-27 15:13:00,2013-06-27 15:27:00,77,852,19,Loomis St & Taylor St,55,Halsted St & James M Rochford St,casual,NaN,NaN

In [394]:
df.to_csv("2013-2020.csv", index=False)

# data datetime di csv sudah aman dan seragam tapi biar datetime type sesuai saat di read kita pakai parsedate

In [586]:
df = pd.read_csv("2013-2020.csv", parse_dates=['starttime', 'stoptime'])

C:\Users\Bocah\AppData\Local\Temp\ipykernel_21780\3105786027.py:1: DtypeWarning: Columns (4,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("2013-2020.csv", parse_dates=['starttime', 'stoptime'])

In [587]:
df.head()

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,4118,2013-06-27 12:11:00,2013-06-27 12:16:00,480,316,85,Michigan Ave & Oak St,28,Larrabee St & Menomonee St,casual,NaN,NaN
1,4275,2013-06-27 14:44:00,2013-06-27 14:45:00,77,64,32,Racine Ave & Congress Pkwy,32,Racine Ave & Congress Pkwy,casual,NaN,NaN
2,4291,2013-06-27 14:58:00,2013-06-27 15:05:00,77,433,32,Racine Ave & Congress Pkwy,19,Loomis St & Taylor St,casual,NaN,NaN
3,4316,2013-06-27 15:06:00,2013-06-27 15:09:00,77,123,19,Loomis St & Taylor St,19,Loomis St & Taylor St,casual,NaN,NaN
4,4342,2013-06-27 15:13:00,2013-06-27 15:27:00,77,852,19,Loomis St & Taylor St,55,Halsted St & James M Rochford St,casual,NaN,NaN

In [588]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21243344 entries, 0 to 21243343
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   starttime          datetime64[ns]
 2   stoptime           datetime64[ns]
 3   bikeid             int64
 4   tripduration       object
 5   from_station_id    int64
 6   from_station_name  object
 7   to_station_id      int64
 8   to_station_name    object
 9   usertype           object
 10  gender             object
 11  birthyear          float64
dtypes: datetime64[ns](2), float64(1), int64(4), object(5)
memory usage: 1.9+ GB

In [589]:
df.describe()

,trip_id,starttime,stoptime,bikeid,from_station_id,to_station_id,birthyear
count,2.124334e+07,21243344,21243344,2.124334e+07,2.124334e+07,2.124334e+07,1.597021e+07
mean,1.353282e+07,2017-02-15 05:57:16.363474688,2017-02-15 06:16:33.275763200,2.900297e+03,1.800296e+02,1.804237e+02,1.981561e+03
min,3.940000e+03,2013-06-27 01:06:00,2013-06-27 09:46:00,1.000000e+00,1.000000e+00,1.000000e+00,1.910000e+03
25%,7.186575e+06,2015-08-30 09:16:00,2015-08-30 09:32:45,1.346000e+03,7.500000e+01,7.500000e+01,1.976000e+03
50%,1.375498e+07,2017-04-22 18:14:40.500000,2017-04-22 18:34:42.500000,2.705000e+03,1.570000e+02,1.570000e+02,1.985000e+03
75%,2.000710e+07,2018-08-07 18:41:35.500000,2018-08-07 18:59:32,4.387000e+03,2.680000e+02,2.680000e+02,1.990000e+03
max,2.596290e+07,2019-12-31 23:57:17,2020-01-21 13:54:35,6.946000e+03,6.730000e+02,6.730000e+02,2.004000e+03
std,7.458730e+06,NaN,NaN,1.813878e+03,1.320196e+02,1.321890e+02,1.086242e+01

# Bikeid

In [591]:
len(df["bikeid"].unique())

6525

In [592]:
df["bikeid"].isnull().sum()

0

# TripDuration

In [594]:
df["tripduration"].isnull().sum()

0

In [595]:
df["tripduration"].unique()

array([316, 64, 433, ..., '162,136.0', '88,671.0', '64,681.0'],
      dtype=object)

In [596]:
df['tripduration'] = df['tripduration'].astype(str).str.replace(',', '', regex=False)

In [597]:
df['tripduration'] = pd.to_numeric(df['tripduration'], errors='coerce')

In [598]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21243344 entries, 0 to 21243343
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   starttime          datetime64[ns]
 2   stoptime           datetime64[ns]
 3   bikeid             int64
 4   tripduration       float64
 5   from_station_id    int64
 6   from_station_name  object
 7   to_station_id      int64
 8   to_station_name    object
 9   usertype           object
 10  gender             object
 11  birthyear          float64
dtypes: datetime64[ns](2), float64(2), int64(4), object(4)
memory usage: 1.9+ GB

In [599]:
df["tripduration"].unique()

array([3.16000e+02, 6.40000e+01, 4.33000e+02, ..., 1.62136e+05,
       8.86710e+04, 6.46810e+04])

In [600]:
df['tripduration'] = df['tripduration'].astype('Int64')

In [601]:
df["tripduration"].unique()

<IntegerArray>
[   316,     64,    433,    123,    852,  10105,   1094,   1020,   3419,
    653,
 ...
  34461,  64468,  55258, 179757,  43375, 203471, 162175, 162136,  88671,
  64681]
Length: 41486, dtype: Int64

In [602]:
df["tripduration"].isnull().sum()

0

In [603]:
df.describe()

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,to_station_id,birthyear
count,2.124334e+07,21243344,21243344,2.124334e+07,21243344.0,2.124334e+07,2.124334e+07,1.597021e+07
mean,1.353282e+07,2017-02-15 05:57:16.363474688,2017-02-15 06:16:33.275763200,2.900297e+03,1156.915437,1.800296e+02,1.804237e+02,1.981561e+03
min,3.940000e+03,2013-06-27 01:06:00,2013-06-27 09:46:00,1.000000e+00,60.0,1.000000e+00,1.000000e+00,1.910000e+03
25%,7.186575e+06,2015-08-30 09:16:00,2015-08-30 09:32:45,1.346000e+03,411.0,7.500000e+01,7.500000e+01,1.976000e+03
50%,1.375498e+07,2017-04-22 18:14:40.500000,2017-04-22 18:34:42.500000,2.705000e+03,707.0,1.570000e+02,1.570000e+02,1.985000e+03
75%,2.000710e+07,2018-08-07 18:41:35.500000,2018-08-07 18:59:32,4.387000e+03,1210.0,2.680000e+02,2.680000e+02,1.990000e+03
max,2.596290e+07,2019-12-31 23:57:17,2020-01-21 13:54:35,6.946000e+03,14336400.0,6.730000e+02,6.730000e+02,2.004000e+03
std,7.458730e+06,NaN,NaN,1.813878e+03,19538.361738,1.320196e+02,1.321890e+02,1.086242e+01

In [604]:
print("\n10 Teratas Trip Duration (Detik):")
print(df['tripduration'].nlargest(100))

10 Teratas Trip Duration (Detik):
13940946    14336400
13853069    14294100
13901545    13557600
14287269    13453200
14203546    12889300
              ...
15686284     4751530
19748791     4751266
14372232     4732670
19343132     4680077
19319437     4611739
Name: tripduration, Length: 100, dtype: Int64

In [605]:
df.loc[[13940946, 13853069, 13901545, 14287269, 14203546]]

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
13940946,17681646,2018-02-03 15:02:50,2018-07-19 14:23:31,471,14336400,195,Columbus Dr & Randolph St,433,Kedzie Ave & Harrison St,casual,NaN,NaN
13853069,17576039,2018-01-12 02:20:15,2018-06-26 13:55:00,496,14294100,182,Wells St & Elm St,360,DIVVY Map Frame B/C Station,casual,NaN,NaN
13901545,17634739,2018-01-25 19:56:04,2018-07-01 18:56:21,5956,13557600,585,Cottage Grove Ave & 83rd St,392,Perry Ave & 69th St,member,Male,1997.0
14287269,18095986,2018-04-15 20:47:22,2018-09-18 13:47:42,5779,13453200,119,Ashland Ave & Lake St (Temp),360,DIVVY Map Frame B/C Station,casual,NaN,NaN
14203546,17993581,2018-03-30 16:57:12,2018-08-26 21:19:34,426,12889300,35,Streeter Dr & Grand Ave,360,DIVVY Map Frame B/C Station,casual,NaN,NaN

In [606]:
outliers_count = df[df['tripduration'] > 86400].shape[0]

print(f"Jumlah perjalanan yang lebih dari 24 jam: {outliers_count:,} baris")

Jumlah perjalanan yang lebih dari 24 jam: 3,359 baris

In [607]:
persentase = (outliers_count / len(df)) * 100
print(f"Persentase data kotor: {persentase:.4f}% dari total data")

Persentase data kotor: 0.0158% dari total data

In [608]:
print("total baris sebelum dibuang:", len(df))

total baris sebelum dibuang: 21243344

# Mengahapus tripduration yang lebih dari 24 jam karena ada issue lain terkait hal itu

In [610]:
df = df[df['tripduration'] <= 86400].reset_index(drop=True)

In [611]:
print("3,359 baris dibuang menjadikan total baris saat ini :", len(df))

3,359 baris dibuang menjadikan total baris saat ini : 21239985

In [612]:
df.head()

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,4118,2013-06-27 12:11:00,2013-06-27 12:16:00,480,316,85,Michigan Ave & Oak St,28,Larrabee St & Menomonee St,casual,NaN,NaN
1,4275,2013-06-27 14:44:00,2013-06-27 14:45:00,77,64,32,Racine Ave & Congress Pkwy,32,Racine Ave & Congress Pkwy,casual,NaN,NaN
2,4291,2013-06-27 14:58:00,2013-06-27 15:05:00,77,433,32,Racine Ave & Congress Pkwy,19,Loomis St & Taylor St,casual,NaN,NaN
3,4316,2013-06-27 15:06:00,2013-06-27 15:09:00,77,123,19,Loomis St & Taylor St,19,Loomis St & Taylor St,casual,NaN,NaN
4,4342,2013-06-27 15:13:00,2013-06-27 15:27:00,77,852,19,Loomis St & Taylor St,55,Halsted St & James M Rochford St,casual,NaN,NaN

In [613]:
df["tripduration"].max()

86400

In [614]:
df["tripduration"].min()

60

# from_station_id & from_station_name

In [616]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21239985 entries, 0 to 21239984
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   starttime          datetime64[ns]
 2   stoptime           datetime64[ns]
 3   bikeid             int64
 4   tripduration       Int64
 5   from_station_id    int64
 6   from_station_name  object
 7   to_station_id      int64
 8   to_station_name    object
 9   usertype           object
 10  gender             object
 11  birthyear          float64
dtypes: Int64(1), datetime64[ns](2), float64(1), int64(4), object(4)
memory usage: 1.9+ GB

In [617]:
df["from_station_id"].isnull().sum()

0

In [618]:
df["from_station_name"].isnull().sum()

0

In [619]:
len(df["from_station_id"].unique())

633

In [620]:
len(df["from_station_name"].unique())

749

In [621]:
df_nama_ganda = (
    df.groupby('from_station_id')['from_station_name']
    .unique()
    .reset_index()
)

df_nama_ganda['jumlah_nama'] = df_nama_ganda['from_station_name'].apply(len)

df_nama_ganda = df_nama_ganda[df_nama_ganda['jumlah_nama'] > 1].sort_values(by='jumlah_nama', ascending=False)

pd.set_option('display.max_colwidth', None)
df_nama_ganda.head(1)

,from_station_id,from_station_name,jumlah_nama
406,437,"[Washtenaw Ave & 15th St, Washtenaw Ave & 15th St (*), Washtenaw Ave & Ogden Ave (*), Washtenaw Ave & Ogden Ave]",4

# to_station_id & to_station_name

In [623]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21239985 entries, 0 to 21239984
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   starttime          datetime64[ns]
 2   stoptime           datetime64[ns]
 3   bikeid             int64
 4   tripduration       Int64
 5   from_station_id    int64
 6   from_station_name  object
 7   to_station_id      int64
 8   to_station_name    object
 9   usertype           object
 10  gender             object
 11  birthyear          float64
dtypes: Int64(1), datetime64[ns](2), float64(1), int64(4), object(4)
memory usage: 1.9+ GB

In [624]:
df["to_station_id"].isnull().sum()

0

In [625]:
df["to_station_name"].isnull().sum()

0

In [626]:
len(df["to_station_id"].unique())

633

In [627]:
len(df["to_station_name"].unique())

749

In [628]:
df.head()

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,4118,2013-06-27 12:11:00,2013-06-27 12:16:00,480,316,85,Michigan Ave & Oak St,28,Larrabee St & Menomonee St,casual,NaN,NaN
1,4275,2013-06-27 14:44:00,2013-06-27 14:45:00,77,64,32,Racine Ave & Congress Pkwy,32,Racine Ave & Congress Pkwy,casual,NaN,NaN
2,4291,2013-06-27 14:58:00,2013-06-27 15:05:00,77,433,32,Racine Ave & Congress Pkwy,19,Loomis St & Taylor St,casual,NaN,NaN
3,4316,2013-06-27 15:06:00,2013-06-27 15:09:00,77,123,19,Loomis St & Taylor St,19,Loomis St & Taylor St,casual,NaN,NaN
4,4342,2013-06-27 15:13:00,2013-06-27 15:27:00,77,852,19,Loomis St & Taylor St,55,Halsted St & James M Rochford St,casual,NaN,NaN

# usertype

In [630]:
df["usertype"].unique()

array(['casual', 'member'], dtype=object)

In [631]:
df["usertype"].isnull().sum()

0

In [632]:
df['usertype'] = df['usertype'].astype('category')

In [633]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21239985 entries, 0 to 21239984
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   starttime          datetime64[ns]
 2   stoptime           datetime64[ns]
 3   bikeid             int64
 4   tripduration       Int64
 5   from_station_id    int64
 6   from_station_name  object
 7   to_station_id      int64
 8   to_station_name    object
 9   usertype           category
 10  gender             object
 11  birthyear          float64
dtypes: Int64(1), category(1), datetime64[ns](2), float64(1), int64(4), object(3)
memory usage: 1.8+ GB

In [680]:
df.tail()

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
21239980,25962900,2019-12-31 23:56:13,2020-01-01 00:15:45,2196,1172,112,Green St & Randolph St,225,Halsted St & Dickens Ave,member,Male,1981.0
21239981,25962901,2019-12-31 23:56:34,2020-01-01 00:22:08,4877,1533,90,Millennium Park,90,Millennium Park,member,Male,1992.0
21239982,25962902,2019-12-31 23:57:05,2020-01-01 00:05:46,863,520,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,member,Male,1967.0
21239983,25962903,2019-12-31 23:57:11,2020-01-01 00:05:45,2637,514,623,Michigan Ave & 8th St,52,Michigan Ave & Lake St,member,Female,1970.0
21239984,25962904,2019-12-31 23:57:17,2019-12-31 23:59:18,5930,120,256,Broadway & Sheridan Rd,240,Sheridan Rd & Irving Park Rd,member,Male,1982.0

In [682]:
df.to_csv('divvy_cleaned_2013_2020.csv', index=False)

print("✅ Data 2013-2020 yang sudah bersih berhasil disimpan!")

✅ Data 2013-2020 yang sudah bersih berhasil disimpan!

# PEMBERSIHAN UNTUK 2020-2026

In [684]:
import gc
del df
gc.collect()

5627

In [692]:
%reset -f out

Flushing output cache (529 entries)

In [720]:
tf = pd.read_csv("2020-2026.csv")
tf.head()

C:\Users\Bocah\AppData\Local\Temp\ipykernel_21780\2462306591.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  tf = pd.read_csv("2020-2026.csv")

,trip_id,rideable_type,starttime,stoptime,from_station_name,from_station_id,to_station_name,to_station_id,start_lat,start_lng,end_lat,end_lng,usertype,tripduration
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152.0,41.8964,-87.6610,41.9322,-87.6586,member,1609
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:54,2020-04-17 17:17:03,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499.0,41.9244,-87.7154,41.9306,-87.7238,member,489
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:13,2020-04-01 18:08:36,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255.0,41.8945,-87.6179,41.8679,-87.6230,member,863
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:19,2020-04-07 13:02:31,California Ave & Division St,216,Wood St & Augusta Blvd,657.0,41.9030,-87.6975,41.8992,-87.6722,member,732
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:59,2020-04-18 11:15:54,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323.0,41.8902,-87.6262,41.9695,-87.6547,casual,3175

In [722]:
tf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33696132 entries, 0 to 33696131
Data columns (total 14 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            object
 1   rideable_type      object
 2   starttime          object
 3   stoptime           object
 4   from_station_name  object
 5   from_station_id    object
 6   to_station_name    object
 7   to_station_id      object
 8   start_lat          float64
 9   start_lng          float64
 10  end_lat            float64
 11  end_lng            float64
 12  usertype           object
 13  tripduration       int64
dtypes: float64(4), int64(1), object(9)
memory usage: 3.5+ GB

In [724]:
len(tf)

33696132

In [726]:
tf.describe()

          start_lat     start_lng       end_lat       end_lng  tripduration
count  3.369613e+07  3.369613e+07  3.365993e+07  3.365993e+07  3.369613e+07
mean   4.190257e+01 -8.764654e+01  4.190290e+01 -8.764676e+01  1.140787e+03
std    4.513815e-02  2.786700e-02  5.308470e-02  7.351622e-02  1.165582e+04
min    4.163000e+01 -8.794000e+01  0.000000e+00 -1.440500e+02 -1.742998e+06
25%    4.188114e+01 -8.766000e+01  4.188132e+01 -8.766000e+01  3.500000e+02
50%    4.189883e+01 -8.764299e+01  4.189958e+01 -8.764312e+01  6.220000e+02
75%    4.193000e+01 -8.762952e+01  4.193000e+01 -8.762954e+01  1.124000e+03
max    4.563503e+01 -7.379648e+01  8.796000e+01  1.525300e+02  9.387024e+06

# trip_id

In [729]:
tf["trip_id"].isnull().sum()

0

# rideable_type

In [732]:
tf["rideable_type"].unique()

array(['docked_bike', 'electric_bike', 'classic_bike', 'electric_scooter'],
      dtype=object)

In [734]:
tf["rideable_type"].nunique()

4

In [738]:
tf["rideable_type"].isnull().sum()

0

In [736]:
tf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33696132 entries, 0 to 33696131
Data columns (total 14 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            object
 1   rideable_type      object
 2   starttime          object
 3   stoptime           object
 4   from_station_name  object
 5   from_station_id    object
 6   to_station_name    object
 7   to_station_id      object
 8   start_lat          float64
 9   start_lng          float64
 10  end_lat            float64
 11  end_lng            float64
 12  usertype           object
 13  tripduration       int64
dtypes: float64(4), int64(1), object(9)
memory usage: 3.5+ GB

In [740]:
tf["rideable_type"] = tf["rideable_type"].astype('category')

In [742]:
tf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33696132 entries, 0 to 33696131
Data columns (total 14 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            object
 1   rideable_type      category
 2   starttime          object
 3   stoptime           object
 4   from_station_name  object
 5   from_station_id    object
 6   to_station_name    object
 7   to_station_id      object
 8   start_lat          float64
 9   start_lng          float64
 10  end_lat            float64
 11  end_lng            float64
 12  usertype           object
 13  tripduration       int64
dtypes: category(1), float64(4), int64(1), object(8)
memory usage: 3.3+ GB

In [744]:
tf.head()

,trip_id,rideable_type,starttime,stoptime,from_station_name,from_station_id,to_station_name,to_station_id,start_lat,start_lng,end_lat,end_lng,usertype,tripduration
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152.0,41.8964,-87.6610,41.9322,-87.6586,member,1609
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:54,2020-04-17 17:17:03,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499.0,41.9244,-87.7154,41.9306,-87.7238,member,489
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:13,2020-04-01 18:08:36,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255.0,41.8945,-87.6179,41.8679,-87.6230,member,863
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:19,2020-04-07 13:02:31,California Ave & Division St,216,Wood St & Augusta Blvd,657.0,41.9030,-87.6975,41.8992,-87.6722,member,732
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:59,2020-04-18 11:15:54,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323.0,41.8902,-87.6262,41.9695,-87.6547,casual,3175

In [747]:
tf["rideable_type"].value_counts()

rideable_type
electric_bike       16178558
classic_bike        13838811
docked_bike          3534426
electric_scooter      144337
Name: count, dtype: int64

# starttime and stoptime

In [749]:

print("1. Sedang memproses starttime (33 juta baris)...")
tf['starttime'] = pd.to_datetime(tf['starttime'], format='mixed', errors='coerce')
print("✅ starttime SELESAI!")

print("\n2. Sedang memproses stoptime (33 juta baris)...")
tf['stoptime'] = pd.to_datetime(tf['stoptime'], format='mixed', errors='coerce')
print("✅ stoptime SELESAI!")

1. Sedang memproses starttime (33 juta baris)...
✅ starttime SELESAI!

2. Sedang memproses stoptime (33 juta baris)...
✅ stoptime SELESAI!

In [751]:
tf.head()

,trip_id,rideable_type,starttime,stoptime,from_station_name,from_station_id,to_station_name,to_station_id,start_lat,start_lng,end_lat,end_lng,usertype,tripduration
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152.0,41.8964,-87.6610,41.9322,-87.6586,member,1609
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:54,2020-04-17 17:17:03,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499.0,41.9244,-87.7154,41.9306,-87.7238,member,489
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:13,2020-04-01 18:08:36,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255.0,41.8945,-87.6179,41.8679,-87.6230,member,863
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:19,2020-04-07 13:02:31,California Ave & Division St,216,Wood St & Augusta Blvd,657.0,41.9030,-87.6975,41.8992,-87.6722,member,732
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:59,2020-04-18 11:15:54,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323.0,41.8902,-87.6262,41.9695,-87.6547,casual,3175

In [753]:
tf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33696132 entries, 0 to 33696131
Data columns (total 14 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            object
 1   rideable_type      category
 2   starttime          datetime64[ns]
 3   stoptime           datetime64[ns]
 4   from_station_name  object
 5   from_station_id    object
 6   to_station_name    object
 7   to_station_id      object
 8   start_lat          float64
 9   start_lng          float64
 10  end_lat            float64
 11  end_lng            float64
 12  usertype           object
 13  tripduration       int64
dtypes: category(1), datetime64[ns](2), float64(4), int64(1), object(6)
memory usage: 3.3+ GB

In [755]:
tf["starttime"].isnull().sum()

0

In [759]:
tf["stoptime"].isnull().sum()

0

# from_station_name and from_station_id and to_station_id and to_station_id

In [762]:
tf["from_station_name"].isnull().sum()

5096536

In [764]:
tf["from_station_id"].isnull().sum()

5097291

In [783]:
tf["to_station_name"].isnull().sum()

5381359

In [785]:
tf["to_station_id"].isnull().sum()

5381961

In [766]:
tf.tail()

,trip_id,rideable_type,starttime,stoptime,from_station_name,from_station_id,to_station_name,to_station_id,start_lat,start_lng,end_lat,end_lng,usertype,tripduration
33696127,ADDAA33CEBCAE733,docked_bike,2020-03-10 10:40:06,2020-03-10 10:40:07,HQ QR,675,HQ QR,675.0,41.8899,-87.6803,41.8899,-87.6803,casual,1
33696128,82B10FA3994BC66A,docked_bike,2020-03-07 15:25:55,2020-03-07 16:14:03,Rush St & Superior St,161,Sheridan Rd & Irving Park Rd,240.0,41.8958,-87.6259,41.9542,-87.6544,member,2888
33696129,AA0D5AAA0B59C8AA,docked_bike,2020-03-01 13:12:38,2020-03-01 13:38:29,Clark St & Lincoln Ave,141,Ashland Ave & Division St,210.0,41.9157,-87.6346,41.9035,-87.6677,casual,1551
33696130,3296360A7BC20FB8,docked_bike,2020-03-07 18:02:45,2020-03-07 18:13:18,Franklin St & Illinois St,672,Stetson Ave & South Water St,264.0,41.8910,-87.6355,41.8868,-87.6223,member,633
33696131,064EC7698E4FF9B3,docked_bike,2020-03-08 13:03:57,2020-03-08 13:32:27,Dearborn St & Erie St,110,Michigan Ave & Oak St,85.0,41.8940,-87.6293,41.9010,-87.6238,casual,1710

In [772]:
tf.loc[tf['from_station_name'].isnull(), 'rideable_type'].value_counts()

rideable_type
electric_bike       5028853
electric_scooter      67649
classic_bike             34
docked_bike               0
Name: count, dtype: int64

In [787]:
tf.loc[tf['to_station_name'].isnull(), 'rideable_type'].value_counts()

rideable_type
electric_bike       5269025
electric_scooter      70340
classic_bike          32858
docked_bike            9136
Name: count, dtype: int64

In [780]:
ada_id_0 = 0 in tf['from_station_id'].unique()

ada_name_v = 'On-Street' in tf['from_station_name'].unique()

print("Apakah angka 0 ada di ID?:", ada_id_0)
print("Apakah 'On-Street / Virtual Station' ada di Name?:", ada_name_v)

Apakah angka 0 ada di ID?: False
Apakah 'On-Street / Virtual Station' ada di Name?: False

In [789]:
print("Sedang melakukan imputasi data stasiun kosong...")

# 1. Mengisi Nama Stasiun dengan 'On-Street'
tf['from_station_name'] = tf['from_station_name'].fillna('On-Street')
tf['to_station_name'] = tf['to_station_name'].fillna('On-Street')

# 2. Mengisi ID Stasiun dengan angka 0
tf['from_station_id'] = tf['from_station_id'].fillna(0)
tf['to_station_id'] = tf['to_station_id'].fillna(0)

print("✅ Imputasi Selesai!")

Sedang melakukan imputasi data stasiun kosong...
✅ Imputasi Selesai!

In [793]:
tf["from_station_name"].isnull().sum()

0

In [805]:
tf["from_station_name"].value_counts()

from_station_name
On-Street                                5096536
Streeter Dr & Grand Ave                   352652
Michigan Ave & Oak St                     226168
Clark St & Elm St                         216351
Wells St & Concord Ln                     207689
                                          ...
Avers Ave & Ogden Ave                          1
Public Rack - Hamlin & 72nd                    1
Public Rack - Corliss Ave & 133rd St           1
Public Rack - Eberhart Ave & 131st St          1
Ewing Ave & 99th St                            1
Name: count, Length: 2619, dtype: int64

In [807]:
tf.head()

,trip_id,rideable_type,starttime,stoptime,from_station_name,from_station_id,to_station_name,to_station_id,start_lat,start_lng,end_lat,end_lng,usertype,tripduration
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152.0,41.8964,-87.6610,41.9322,-87.6586,member,1609
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:54,2020-04-17 17:17:03,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499.0,41.9244,-87.7154,41.9306,-87.7238,member,489
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:13,2020-04-01 18:08:36,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255.0,41.8945,-87.6179,41.8679,-87.6230,member,863
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:19,2020-04-07 13:02:31,California Ave & Division St,216,Wood St & Augusta Blvd,657.0,41.9030,-87.6975,41.8992,-87.6722,member,732
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:59,2020-04-18 11:15:54,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323.0,41.8902,-87.6262,41.9695,-87.6547,casual,3175

In [814]:
tf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33696132 entries, 0 to 33696131
Data columns (total 14 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            object
 1   rideable_type      category
 2   starttime          datetime64[ns]
 3   stoptime           datetime64[ns]
 4   from_station_name  object
 5   from_station_id    object
 6   to_station_name    object
 7   to_station_id      object
 8   start_lat          float64
 9   start_lng          float64
 10  end_lat            float64
 11  end_lng            float64
 12  usertype           object
 13  tripduration       int64
dtypes: category(1), datetime64[ns](2), float64(4), int64(1), object(6)
memory usage: 3.3+ GB

In [834]:
tf["from_station_id"].nunique()

5386

In [836]:
tf["to_station_id"].nunique()

5115

# Tripduration

In [853]:
tf["tripduration"].value_counts()

tripduration
295       36634
292       36596
297       36574
312       36564
302       36543
          ...
23790         1
22848         1
29548         1
163779        1
175616        1
Name: count, Length: 53929, dtype: int64

In [855]:
outlier_count = tf[tf["tripduration"] > 86400].shape[0]

print(f"jumlah perjalanan yang lebih dari 24 jam: {outlier_count} baris")

jumlah perjalanan yang lebih dari 24 jam: 33332 baris

In [857]:
presentase = (outlier_count / len(tf)) * 100
print(f"presentase data kotor: {presentase:.4f}% dari total data")

presentase data kotor: 0.0989% dari total data

In [859]:
print("total baris sebelum dibuang", len(tf))

total baris sebelum dibuang 33696132

In [861]:
tf = tf[tf["tripduration"] <= 86400].reset_index(drop=True)

In [865]:
print("33,332 baris dibuang menjadi total baris saat ini:", len(tf))

33,332 baris dibuang menjadi total baris saat ini: 33662800

# start_lat and start_lng and end_lat and end_lng

In [868]:
tf.head()

,trip_id,rideable_type,starttime,stoptime,from_station_name,from_station_id,to_station_name,to_station_id,start_lat,start_lng,end_lat,end_lng,usertype,tripduration
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152.0,41.8964,-87.6610,41.9322,-87.6586,member,1609
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:54,2020-04-17 17:17:03,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499.0,41.9244,-87.7154,41.9306,-87.7238,member,489
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:13,2020-04-01 18:08:36,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255.0,41.8945,-87.6179,41.8679,-87.6230,member,863
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:19,2020-04-07 13:02:31,California Ave & Division St,216,Wood St & Augusta Blvd,657.0,41.9030,-87.6975,41.8992,-87.6722,member,732
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:59,2020-04-18 11:15:54,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323.0,41.8902,-87.6262,41.9695,-87.6547,casual,3175

In [870]:
tf["start_lat"].isnull().sum()

0

In [872]:
tf["start_lng"].isnull().sum()

0

In [874]:
tf["end_lat"].isnull().sum()

7613

In [876]:
tf["end_lng"].isnull().sum()

7613

In [880]:
#langsung kita drop
tf = tf.dropna(subset=['end_lat', 'end_lng'])

In [882]:
len(tf)

33655187

In [884]:
#kita periksa lagi
tf["end_lat"].isnull().sum()

0

In [886]:
tf["end_lng"].isnull().sum()

0

In [891]:
tf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33655187 entries, 0 to 33662799
Data columns (total 14 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            object
 1   rideable_type      category
 2   starttime          datetime64[ns]
 3   stoptime           datetime64[ns]
 4   from_station_name  object
 5   from_station_id    object
 6   to_station_name    object
 7   to_station_id      object
 8   start_lat          float64
 9   start_lng          float64
 10  end_lat            float64
 11  end_lng            float64
 12  usertype           object
 13  tripduration       int64
dtypes: category(1), datetime64[ns](2), float64(4), int64(1), object(6)
memory usage: 3.5+ GB

# usertype

In [893]:
tf["usertype"].unique()

array(['member', 'casual'], dtype=object)

In [895]:
tf["usertype"].isnull().sum()

0

In [897]:
tf["usertype"] = tf["usertype"].astype('category')

C:\Users\Bocah\AppData\Local\Temp\ipykernel_21780\317893992.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tf["usertype"] = tf["usertype"].astype('category')

In [899]:
tf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33655187 entries, 0 to 33662799
Data columns (total 14 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            object
 1   rideable_type      category
 2   starttime          datetime64[ns]
 3   stoptime           datetime64[ns]
 4   from_station_name  object
 5   from_station_id    object
 6   to_station_name    object
 7   to_station_id      object
 8   start_lat          float64
 9   start_lng          float64
 10  end_lat            float64
 11  end_lng            float64
 12  usertype           category
 13  tripduration       int64
dtypes: category(2), datetime64[ns](2), float64(4), int64(1), object(5)
memory usage: 3.3+ GB

In [901]:
tf.head()

,trip_id,rideable_type,starttime,stoptime,from_station_name,from_station_id,to_station_name,to_station_id,start_lat,start_lng,end_lat,end_lng,usertype,tripduration
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152.0,41.8964,-87.6610,41.9322,-87.6586,member,1609
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:54,2020-04-17 17:17:03,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499.0,41.9244,-87.7154,41.9306,-87.7238,member,489
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:13,2020-04-01 18:08:36,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255.0,41.8945,-87.6179,41.8679,-87.6230,member,863
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:19,2020-04-07 13:02:31,California Ave & Division St,216,Wood St & Augusta Blvd,657.0,41.9030,-87.6975,41.8992,-87.6722,member,732
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:59,2020-04-18 11:15:54,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323.0,41.8902,-87.6262,41.9695,-87.6547,casual,3175

In [903]:
tf.tail()

,trip_id,rideable_type,starttime,stoptime,from_station_name,from_station_id,to_station_name,to_station_id,start_lat,start_lng,end_lat,end_lng,usertype,tripduration
33662795,ADDAA33CEBCAE733,docked_bike,2020-03-10 10:40:06,2020-03-10 10:40:07,HQ QR,675,HQ QR,675.0,41.8899,-87.6803,41.8899,-87.6803,casual,1
33662796,82B10FA3994BC66A,docked_bike,2020-03-07 15:25:55,2020-03-07 16:14:03,Rush St & Superior St,161,Sheridan Rd & Irving Park Rd,240.0,41.8958,-87.6259,41.9542,-87.6544,member,2888
33662797,AA0D5AAA0B59C8AA,docked_bike,2020-03-01 13:12:38,2020-03-01 13:38:29,Clark St & Lincoln Ave,141,Ashland Ave & Division St,210.0,41.9157,-87.6346,41.9035,-87.6677,casual,1551
33662798,3296360A7BC20FB8,docked_bike,2020-03-07 18:02:45,2020-03-07 18:13:18,Franklin St & Illinois St,672,Stetson Ave & South Water St,264.0,41.8910,-87.6355,41.8868,-87.6223,member,633
33662799,064EC7698E4FF9B3,docked_bike,2020-03-08 13:03:57,2020-03-08 13:32:27,Dearborn St & Erie St,110,Michigan Ave & Oak St,85.0,41.8940,-87.6293,41.9010,-87.6238,casual,1710

In [905]:
df.to_csv('divvy_cleaned_2020_2026.csv', index=False)

print("✅ Data 2020-2026 yang sudah bersih berhasil disimpan!")

✅ Data 2020-2026 yang sudah bersih berhasil disimpan!

# done! pembersihan 2 data 2013-2020 dan 2020-2026 selesai